# Generated by Django 4.2.2 on 2023-06-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_description_product_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
