# Generated by Django 4.2.2 on 2023-06-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
